In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv(r'D:\dhrumit\sem2\MLP\fracture.csv')
df.head()

,id,age,sex,fracture,weight_kg,height_cm,medication,waiting_time,bmd
0,469,57.052768,F,no fracture,64.0,155.5,Anticonvulsant,18,0.8793
1,8724,75.741225,F,no fracture,78.0,162.0,No medication,56,0.7946
2,6736,70.778900,M,no fracture,73.0,170.5,No medication,10,0.9067
3,24180,78.247175,F,no fracture,60.0,148.0,No medication,14,0.7112
4,17072,54.191877,M,no fracture,55.0,161.0,No medication,20,0.7909

In [7]:
x = df.iloc[:,[1,2,8]]
x

           age sex     bmd
0    57.052768   F  0.8793
1    75.741225   F  0.7946
2    70.778900   M  0.9067
3    78.247175   F  0.7112
4    54.191877   M  0.7909
5    77.177752   M  0.7301
6    56.180618   M  1.0096
7    49.916140   F  0.7310
8    68.408403   M  0.6893
9    66.256648   M  0.9466
10   45.866582   M  0.8015
11   73.970471   F  0.5793
12   60.555417   F  0.9760
13   64.213103   M  0.9184
14   53.395440   M  0.8020
15   66.825462   M  0.8033
16   57.934593   M  0.7978
17   40.232367   M  1.0390
18   69.048179   F  0.7861
19   57.802298   F  0.8254
20   58.191329   F  0.8499
21   46.081550   M  0.8982
22   65.795352   F  0.7738
23   60.189461   F  0.8377
24   54.992184   M  0.8126
25   51.430717   F  0.9234
26   70.198573   M  1.0406
27   77.155020   M  1.0020
28   70.421873   F  0.6250
29   75.015480   M  0.9364
..         ...  ..     ...
139  71.172124   F  0.4076
140  70.947564   M  0.4407
141  74.796883   F  0.4852
142  83.219823   F  0.5555
143  81.979559   M  0.5615
144  85.901595   M  0.6102
145  71.471721   M  0.6297
146  76.732604   F  0.6385
147  83.678357   M  0.6388
148  85.576311   F  0.6409
149  70.810941   F  0.6432
150  68.683288   F  0.6448
151  86.859869   M  0.6495
152  80.060205   M  0.6708
153  61.644504   F  0.6880
154  66.804185   M  0.6882
155  37.461995   M  0.6884
156  63.441966   M  0.6899
157  51.048370   F  0.6904
158  48.523651   F  0.6904
159  41.351200   M  0.7076
160  84.721764   M  0.7085
161  59.076082   M  0.7246
162  50.276059   F  0.7399
163  67.252163   M  0.7745
164  77.982543   M  0.7941
165  50.285303   F  0.7971
166  46.359721   M  0.8037
167  54.788368   M  0.8072
168  69.994822   F  0.8664

[169 rows x 3 columns]

In [8]:
y = df.iloc[:,3].values
y

array(['no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'no fracture',
       'no fracture', 'no fracture', 'no fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture', 'fracture',
       'fracture', 'fracture', 'fracture', 'fracture'], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
x['sex'] = le.fit_transform(df['sex'])
x

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

           age  sex     bmd
0    57.052768    0  0.8793
1    75.741225    0  0.7946
2    70.778900    1  0.9067
3    78.247175    0  0.7112
4    54.191877    1  0.7909
5    77.177752    1  0.7301
6    56.180618    1  1.0096
7    49.916140    0  0.7310
8    68.408403    1  0.6893
9    66.256648    1  0.9466
10   45.866582    1  0.8015
11   73.970471    0  0.5793
12   60.555417    0  0.9760
13   64.213103    1  0.9184
14   53.395440    1  0.8020
15   66.825462    1  0.8033
16   57.934593    1  0.7978
17   40.232367    1  1.0390
18   69.048179    0  0.7861
19   57.802298    0  0.8254
20   58.191329    0  0.8499
21   46.081550    1  0.8982
22   65.795352    0  0.7738
23   60.189461    0  0.8377
24   54.992184    1  0.8126
25   51.430717    0  0.9234
26   70.198573    1  1.0406
27   77.155020    1  1.0020
28   70.421873    0  0.6250
29   75.015480    1  0.9364
..         ...  ...     ...
139  71.172124    0  0.4076
140  70.947564    1  0.4407
141  74.796883    0  0.4852
142  83.219823    0  0.5555
143  81.979559    1  0.5615
144  85.901595    1  0.6102
145  71.471721    1  0.6297
146  76.732604    0  0.6385
147  83.678357    1  0.6388
148  85.576311    0  0.6409
149  70.810941    0  0.6432
150  68.683288    0  0.6448
151  86.859869    1  0.6495
152  80.060205    1  0.6708
153  61.644504    0  0.6880
154  66.804185    1  0.6882
155  37.461995    1  0.6884
156  63.441966    1  0.6899
157  51.048370    0  0.6904
158  48.523651    0  0.6904
159  41.351200    1  0.7076
160  84.721764    1  0.7085
161  59.076082    1  0.7246
162  50.276059    0  0.7399
163  67.252163    1  0.7745
164  77.982543    1  0.7941
165  50.285303    0  0.7971
166  46.359721    1  0.8037
167  54.788368    1  0.8072
168  69.994822    0  0.8664

[169 rows x 3 columns]

In [16]:
y = le.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
lr = LogisticRegression()

In [20]:
lr.fit(x_train,y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [22]:
y_pread = lr.predict(x_test)
y_pread

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [23]:
lr.score(x_test,y_test)

0.8235294117647058